version: '2'
services:
  validator:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: validator
    volumes:
      - ./validator:/home/parity/.local/share/io.parity.ethereum
    entrypoint: /init.sh
    command: --start
    environment:
      NAT_IP: __PUT_YOUR_PUBLIC_IP_ADDRESS_HERE__
      #If you have multiple addresses, you can specify one address for the authority node.
      #AUTH_ADDRESS: 0xab59a1ea1ac9af9f77518b9b4ad80942ade35088
    user: "0:0"
    ports:                                                            
      - 8545:8545                       
      - 8546:8546                                                                             
      - 30303:30303       
